module.exports = {
  LOADER_OPEN: 'LOADER_OPEN',
  LOADER_CLOSE: 'LOADER_CLOSE',
  LOADER_START_READING: 'LOADER_START_READING',
  LOADER_END_READING: 'LOADER_END_READING',
  ADD_FILE: 'LOADER_ADD_FILE',
  SET_SPINE_DATA: 'SET_SPINE_DATA',
  SET_ANIMATION: 'SET_ANIMATION',
  SET_SPINE_ACTION: 'SET_SPINE_ACTION',
  SPINE_ACTION: {
    PLAY: 'PLAY',
    PAUSE: 'PAUSE',
    STOP: 'STOP',
  },
  SET_SPINE_SPEED: 'SET_SPINE_SPEED',
  SET_SPINE_OPACITY: 'SET_SPINE_OPACITY',
  RESET_SPINE_ADJUSTMENTS: 'RESET_SPINE_ADJUSTMENTS',
  RESET: 'RESET',
}
